version: '3'

services:
  db:
    container_name:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
