server:
  port: 8080
spring:
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-23-21-197-231.compute-1.amazonaws.com:5432/d8f6f02hdlefdc?sslmode=requere&user=jriznkneriewsk&password=a6819e2d2c04604e2ba298af803af4f9790a6481bc7782e1e7daece9ca9d52a1
    username: jriznkneriewsk
    password: a6819e2d2c04604e2ba298af803af4f9790a6481bc7782e1e7daece9ca9d52a1
    name: d8f6f02hdlefdc
